name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scan every Monday at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pip-audit

    - name: Run Bandit (Python Security Linter)
      run: |
        bandit -r src/ -f json -o bandit-report.json || true
        bandit -r src/ -f txt
      continue-on-error: true

    - name: Run Safety (Dependency Vulnerability Scanner)
      run: |
        safety check --json --output safety-report.json || true
        safety check --output text
      continue-on-error: true

    - name: Run pip-audit (PyPI Package Auditor)
      run: |
        pip-audit --desc --format json --output pip-audit-report.json || true
        pip-audit --desc
      continue-on-error: true

    - name: SAST Scan with Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/python
          p/flask

    - name: Dependency Review
      if: github.event_name == 'pull_request'
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate

    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          pip-audit-report.json

    - name: Generate security summary
      if: always()
      run: |
        echo "## Security Scan Results 🔒" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Bandit (Code Security)" >> $GITHUB_STEP_SUMMARY
        if [ -f bandit-report.json ]; then
          echo "✅ Bandit scan completed" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Safety (Dependency Vulnerabilities)" >> $GITHUB_STEP_SUMMARY
        if [ -f safety-report.json ]; then
          echo "✅ Safety scan completed" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### pip-audit (PyPI Packages)" >> $GITHUB_STEP_SUMMARY
        if [ -f pip-audit-report.json ]; then
          echo "✅ pip-audit scan completed" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Comment PR with security findings
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🔒 Security Scan Results\n\n';
          
          if (fs.existsSync('bandit-report.json')) {
            comment += '✅ **Bandit**: Code security analysis completed\n';
          }
          if (fs.existsSync('safety-report.json')) {
            comment += '✅ **Safety**: Dependency vulnerability scan completed\n';
          }
          if (fs.existsSync('pip-audit-report.json')) {
            comment += '✅ **pip-audit**: PyPI package audit completed\n';
          }
          
          comment += '\n📊 Full reports available in workflow artifacts.';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
